name: Publish

on:
  push:
    tags: ['v*']

jobs:
  publish:
    runs-on: ubuntu-latest
    
    environment:
      name: publishing
      
    permissions:
      contents: write # for creating GitHub Release
      id-token: write # for OIDC authentication
    
    steps:
      - uses: actions/checkout@v5
        with:
          ref: main
          fetch-depth: 0
      
      - name: Ensure main branch
        run: |
          BRANCHS=$(git branch --contains ${{ github.ref_name }})
          set -- $BRANCHS
          for BRANCH in $BRANCHS; do
            if [[ "$BRANCH" == "main" ]]; then
              exit 0
            fi
          done
          exit 1
      
      - name: install MuJoCo and set MUJOCO_DIR (for compiling to pass)
        run: |
          mkdir -p $HOME/.mujoco && cd $HOME/.mujoco
          wget https://github.com/google-deepmind/mujoco/releases/download/3.3.2/mujoco-3.3.2-linux-x86_64.tar.gz
          tar -xzf mujoco-3.3.2-linux-x86_64.tar.gz
          echo "MUJOCO_DIR=$HOME/.mujoco/mujoco-3.3.2" >> $GITHUB_ENV

      - uses: rust-lang/crates-io-auth-action@v1
        id: cratesio_auth
      
      - name: Trusted Publish to crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.cratesio_auth.outputs.token }}
        run: |
          cargo publish --package rusty_mujoco

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ github.ref_name }} --generate-notes
